import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1784426911468 implements MigrationInterface {
    name = 'Init1784426911468'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL, "name" character varying(64) NOT NULL, "permissionList" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id")); COMMENT ON COLUMN "role"."id" IS '主键ID'; COMMENT ON COLUMN "role"."name" IS '角色名称'; COMMENT ON COLUMN "role"."permissionList" IS '权限列表'; COMMENT ON COLUMN "role"."createdAt" IS '创建时间'`);
        await queryRunner.query(`COMMENT ON TABLE "role" IS '角色表'`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL, "username" character varying(64) NOT NULL, "email" character varying(128) NOT NULL, "passwordHash" character varying(255) NOT NULL, "fullName" character varying(64) NOT NULL, "avatar" character varying(512), "roleId" uuid, "departmentId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")); COMMENT ON COLUMN "user"."id" IS '主键ID'; COMMENT ON COLUMN "user"."username" IS '用户名'; COMMENT ON COLUMN "user"."email" IS '邮箱'; COMMENT ON COLUMN "user"."passwordHash" IS '密码哈希'; COMMENT ON COLUMN "user"."fullName" IS '姓名'; COMMENT ON COLUMN "user"."avatar" IS '头像'; COMMENT ON COLUMN "user"."roleId" IS '角色ID'; COMMENT ON COLUMN "user"."departmentId" IS '部门ID'; COMMENT ON COLUMN "user"."isActive" IS '是否启用'; COMMENT ON COLUMN "user"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_c28e52f758e7bbc53828db9219" ON "user" ("roleId") `);
        await queryRunner.query(`COMMENT ON TABLE "user" IS '用户表'`);
        await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL, "name" character varying(128) NOT NULL, "description" text, "status" character varying(32) NOT NULL DEFAULT 'Active', "workflowInstanceId" uuid, "workflowStatus" character varying(32), "defaultCellCount" integer NOT NULL DEFAULT '17', "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id")); COMMENT ON COLUMN "project"."id" IS '主键ID'; COMMENT ON COLUMN "project"."name" IS '项目名称'; COMMENT ON COLUMN "project"."description" IS '描述'; COMMENT ON COLUMN "project"."status" IS '状态'; COMMENT ON COLUMN "project"."workflowInstanceId" IS '关联流程实例ID'; COMMENT ON COLUMN "project"."workflowStatus" IS '工作流状态(冗余快速查询)'; COMMENT ON COLUMN "project"."defaultCellCount" IS '默认挑选电池数'; COMMENT ON COLUMN "project"."createdBy" IS '创建者ID'; COMMENT ON COLUMN "project"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_2dc881566db51356dbba057458" ON "project" ("workflowInstanceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c714b0a5eaf71cc3a36c242d2e" ON "project" ("createdBy") `);
        await queryRunner.query(`COMMENT ON TABLE "project" IS '项目表'`);
        await queryRunner.query(`CREATE TABLE "experimentCollaborator" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "userId" uuid NOT NULL, "role" character varying(32) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d707e9cc8ccaa1b30b83bd2fe4a" PRIMARY KEY ("id")); COMMENT ON COLUMN "experimentCollaborator"."id" IS '主键ID'; COMMENT ON COLUMN "experimentCollaborator"."experimentId" IS '实验ID'; COMMENT ON COLUMN "experimentCollaborator"."userId" IS 'userId'; COMMENT ON COLUMN "experimentCollaborator"."role" IS '协作角色'; COMMENT ON COLUMN "experimentCollaborator"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_05ba4be00496a7f7b50c8cffae" ON "experimentCollaborator" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb2aacc1444724703a3c1407fd" ON "experimentCollaborator" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6b59fc13761df821a62b4f42d3" ON "experimentCollaborator" ("experimentId", "userId") `);
        await queryRunner.query(`COMMENT ON TABLE "experimentCollaborator" IS '实验协作人员表'`);
        await queryRunner.query(`CREATE TABLE "experiment" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "title" character varying(255) NOT NULL, "content" text, "status" character varying(32) NOT NULL DEFAULT 'Draft', "metadata" jsonb, "workflowStepName" character varying(64), "aiAnalysisOutput" text, "versionNo" integer NOT NULL DEFAULT '1', "reviewerId" uuid, "reviewComment" text, "reviewedAt" TIMESTAMP, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f6eec215c62eec1e0fde987caf" PRIMARY KEY ("id")); COMMENT ON COLUMN "experiment"."id" IS '主键ID'; COMMENT ON COLUMN "experiment"."projectId" IS '项目ID'; COMMENT ON COLUMN "experiment"."title" IS '实验标题'; COMMENT ON COLUMN "experiment"."content" IS '实验内容'; COMMENT ON COLUMN "experiment"."status" IS '状态'; COMMENT ON COLUMN "experiment"."metadata" IS '元数据'; COMMENT ON COLUMN "experiment"."workflowStepName" IS '关联流程步骤名称'; COMMENT ON COLUMN "experiment"."aiAnalysisOutput" IS 'AI分析输出'; COMMENT ON COLUMN "experiment"."versionNo" IS '版本号'; COMMENT ON COLUMN "experiment"."reviewerId" IS '审核人ID'; COMMENT ON COLUMN "experiment"."reviewComment" IS '审核意见'; COMMENT ON COLUMN "experiment"."reviewedAt" IS '审核时间'; COMMENT ON COLUMN "experiment"."createdBy" IS '创建者ID'; COMMENT ON COLUMN "experiment"."createdAt" IS '创建时间'; COMMENT ON COLUMN "experiment"."updatedAt" IS '更新时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_515a4754daa77993362776c559" ON "experiment" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f55aeb096e324c495f65d0884d" ON "experiment" ("reviewerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64493affb7ed37cb8c0b58ac0c" ON "experiment" ("createdBy") `);
        await queryRunner.query(`COMMENT ON TABLE "experiment" IS '实验表'`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL, "name" character varying(128) NOT NULL, "type" character varying(64) NOT NULL, "lotNumber" character varying(64), "quantity" character varying(64), "storageLocation" character varying(128), "purity" character varying(64), "status" character varying(32) NOT NULL DEFAULT 'In Stock', "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id")); COMMENT ON COLUMN "inventory"."id" IS '主键ID'; COMMENT ON COLUMN "inventory"."name" IS '物品名称'; COMMENT ON COLUMN "inventory"."type" IS '物品类型'; COMMENT ON COLUMN "inventory"."lotNumber" IS '批次号'; COMMENT ON COLUMN "inventory"."quantity" IS '数量'; COMMENT ON COLUMN "inventory"."storageLocation" IS '储存位置'; COMMENT ON COLUMN "inventory"."purity" IS '纯度'; COMMENT ON COLUMN "inventory"."status" IS '状态'; COMMENT ON COLUMN "inventory"."lastUsedAt" IS '最后使用时间'; COMMENT ON COLUMN "inventory"."createdAt" IS '创建时间'`);
        await queryRunner.query(`COMMENT ON TABLE "inventory" IS '库存表'`);
        await queryRunner.query(`CREATE TABLE "attachment" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "fileName" character varying(255) NOT NULL, "filePath" character varying(512) NOT NULL, "fileSize" integer NOT NULL, "mimeType" character varying(128) NOT NULL, "uploadedBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2a80c3a8d467f08a750ac4b420" PRIMARY KEY ("id")); COMMENT ON COLUMN "attachment"."id" IS '主键ID'; COMMENT ON COLUMN "attachment"."experimentId" IS '实验ID'; COMMENT ON COLUMN "attachment"."fileName" IS '文件名'; COMMENT ON COLUMN "attachment"."filePath" IS '文件路径'; COMMENT ON COLUMN "attachment"."fileSize" IS '文件大小'; COMMENT ON COLUMN "attachment"."mimeType" IS '媒体类型'; COMMENT ON COLUMN "attachment"."uploadedBy" IS '上传者ID'; COMMENT ON COLUMN "attachment"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_879e0f0818cc2e9294aa9fdcd9" ON "attachment" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce931a70e87bef5768e1ee3b10" ON "attachment" ("uploadedBy") `);
        await queryRunner.query(`COMMENT ON TABLE "attachment" IS '附件表'`);
        await queryRunner.query(`CREATE TABLE "versionHistory" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "versionNumber" integer NOT NULL, "changeSummary" character varying(255), "snapshot" jsonb, "updatedBy" uuid NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_db888aac2b4a7e17e05f1ce12a0" PRIMARY KEY ("id")); COMMENT ON COLUMN "versionHistory"."id" IS '主键ID'; COMMENT ON COLUMN "versionHistory"."experimentId" IS '实验ID'; COMMENT ON COLUMN "versionHistory"."versionNumber" IS '版本号'; COMMENT ON COLUMN "versionHistory"."changeSummary" IS '变更摘要'; COMMENT ON COLUMN "versionHistory"."snapshot" IS '快照数据'; COMMENT ON COLUMN "versionHistory"."updatedBy" IS '更新者ID'; COMMENT ON COLUMN "versionHistory"."updatedAt" IS '更新时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_c549e9092793b630f713f52240" ON "versionHistory" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a48644f8cf5c8a91b72017b4e6" ON "versionHistory" ("updatedBy") `);
        await queryRunner.query(`COMMENT ON TABLE "versionHistory" IS '版本历史表'`);
        await queryRunner.query(`CREATE TABLE "experiment_comment" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "userId" uuid NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7590f3d71c4cc8569ebc949a4e4" PRIMARY KEY ("id")); COMMENT ON COLUMN "experiment_comment"."id" IS '主键ID'; COMMENT ON COLUMN "experiment_comment"."experimentId" IS '实验ID'; COMMENT ON COLUMN "experiment_comment"."userId" IS '评论者用户ID'; COMMENT ON COLUMN "experiment_comment"."content" IS '评论内容'; COMMENT ON COLUMN "experiment_comment"."createdAt" IS '创建时间'; COMMENT ON COLUMN "experiment_comment"."updatedAt" IS '更新时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_9f4c51881e0109ea728240a4ef" ON "experiment_comment" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd6bb290d536ed57958a54bd84" ON "experiment_comment" ("userId") `);
        await queryRunner.query(`COMMENT ON TABLE "experiment_comment" IS '实验评论表'`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL, "userId" uuid NOT NULL, "type" character varying(64) NOT NULL, "payload" jsonb, "relatedExperimentId" uuid, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id")); COMMENT ON COLUMN "notification"."id" IS '主键ID'; COMMENT ON COLUMN "notification"."userId" IS '接收者用户ID'; COMMENT ON COLUMN "notification"."type" IS '通知类型(如 REVIEW_SUBMITTED)'; COMMENT ON COLUMN "notification"."payload" IS '附加负载数据'; COMMENT ON COLUMN "notification"."relatedExperimentId" IS '关联实验ID'; COMMENT ON COLUMN "notification"."isRead" IS '是否已读'; COMMENT ON COLUMN "notification"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_1ced25315eb974b73391fb1c81" ON "notification" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_080ab397c379af09b9d2169e5b" ON "notification" ("isRead") `);
        await queryRunner.query(`COMMENT ON TABLE "notification" IS '系统通知表'`);
        await queryRunner.query(`CREATE TABLE "processData" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellId" character varying(64) NOT NULL, "m0" numeric(18,6), "m1" numeric(18,6), "m2" numeric(18,6), "v0" numeric(18,6), "v1" numeric(18,6), "fu0" numeric(18,6), "fr0" numeric(18,6), "fq1" numeric(18,6), "fq2" numeric(18,6), "fu1" numeric(18,6), "fr1" numeric(18,6), "fu2" numeric(18,6), "fr2" numeric(18,6), "m3" numeric(18,6), "m4" numeric(18,6), "gu0" numeric(18,6), "gr0" numeric(18,6), "gqc1" numeric(18,6), "gqd1" numeric(18,6), "gqc2" numeric(18,6), "gu1" numeric(18,6), "gr1" numeric(18,6), "mIn" numeric(18,6), "mLoss" numeric(18,6), "mHold" numeric(18,6), "fq" numeric(18,6), "qdFirst" numeric(18,6), "fvg" numeric(18,6), "ku" numeric(18,6), "qcFirst" numeric(18,6), "ceFirst" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2d9fe649e96f3f40459e9b437b9" PRIMARY KEY ("id")); COMMENT ON COLUMN "processData"."id" IS '主键ID'; COMMENT ON COLUMN "processData"."experimentId" IS '实验ID'; COMMENT ON COLUMN "processData"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "processData"."cellId" IS '电芯编码'; COMMENT ON COLUMN "processData"."m0" IS '注液前电芯重(m0)'; COMMENT ON COLUMN "processData"."m1" IS '预充后电芯重(m1)'; COMMENT ON COLUMN "processData"."m2" IS '二封后电芯重(m2)'; COMMENT ON COLUMN "processData"."v0" IS '二封前OCV(v0)'; COMMENT ON COLUMN "processData"."v1" IS '二封后OCV(v1)'; COMMENT ON COLUMN "processData"."fu0" IS '化成前OCV(fu0)'; COMMENT ON COLUMN "processData"."fr0" IS '化成前ACIR(fr0)'; COMMENT ON COLUMN "processData"."fq1" IS '化成充电容量(fq1)'; COMMENT ON COLUMN "processData"."fq2" IS '化成放电容量(fq2)'; COMMENT ON COLUMN "processData"."fu1" IS '化成后电压1(fu1)'; COMMENT ON COLUMN "processData"."fr1" IS '化成后电阻1(fr1)'; COMMENT ON COLUMN "processData"."fu2" IS '化成后电压2(fu2)'; COMMENT ON COLUMN "processData"."fr2" IS '化成后电阻2(fr2)'; COMMENT ON COLUMN "processData"."m3" IS '二封前称重(m3)'; COMMENT ON COLUMN "processData"."m4" IS '二封后称重(m4)'; COMMENT ON COLUMN "processData"."gu0" IS '分容前OCV(gu0)'; COMMENT ON COLUMN "processData"."gr0" IS '分容前ACIR(gr0)'; COMMENT ON COLUMN "processData"."gqc1" IS '分容充电容量1(gqc1)'; COMMENT ON COLUMN "processData"."gqd1" IS '分容放电容量1(gqd1)'; COMMENT ON COLUMN "processData"."gqc2" IS '分容充电容量2(gqc2)'; COMMENT ON COLUMN "processData"."gu1" IS '分容后电压(gu1)'; COMMENT ON COLUMN "processData"."gr1" IS '分容后电阻(gr1)'; COMMENT ON COLUMN "processData"."mIn" IS '注液量 mIn=m1-m0 (g)'; COMMENT ON COLUMN "processData"."mLoss" IS '失液量 mLoss=m1-m2 (g)'; COMMENT ON COLUMN "processData"."mHold" IS '保液量 mHold=m4-m0 (g)'; COMMENT ON COLUMN "processData"."fq" IS '化成充总容量 fq=fq1+fq2 (Ah)'; COMMENT ON COLUMN "processData"."qdFirst" IS '首次放电容量 qdFirst=gqd1 (Ah)'; COMMENT ON COLUMN "processData"."fvg" IS '化成产气量 fvg=(v1-v0)/qdFirst (mL/Ah)'; COMMENT ON COLUMN "processData"."ku" IS '老化电压降 ku=fu1-fu2 (V)'; COMMENT ON COLUMN "processData"."qcFirst" IS '首次充电容量 qcFirst=fq+gqc1 (Ah)'; COMMENT ON COLUMN "processData"."ceFirst" IS '首圈库比效率 ceFirst=qdFirst/qcFirst*100 (%)'; COMMENT ON COLUMN "processData"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_0504697d5e858d8ee01aa0cbe8" ON "processData" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b024f6e1e27264bcb8109d6d44" ON "processData" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3f758e69283ec92a398ee6585" ON "processData" ("cellId") `);
        await queryRunner.query(`COMMENT ON TABLE "processData" IS '制程数据表'`);
        await queryRunner.query(`CREATE TABLE "calendarLife" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "dayCount" integer NOT NULL, "q" numeric(18,6), "dq" numeric(18,6), "ddcr" numeric(18,6), "cdcr" numeric(18,6), "u" numeric(18,6), "r" numeric(18,6), "qRetention" numeric(18,6), "qRecovery" numeric(18,6), "ddcrGrowth" numeric(18,6), "cdcrGrowth" numeric(18,6), "uGrowth" numeric(18,6), "rGrowth" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c99ca2561ebc5cf8dd97c28907" PRIMARY KEY ("id")); COMMENT ON COLUMN "calendarLife"."id" IS '主键ID'; COMMENT ON COLUMN "calendarLife"."experimentId" IS '实验ID'; COMMENT ON COLUMN "calendarLife"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "calendarLife"."cellName" IS '电芯名称'; COMMENT ON COLUMN "calendarLife"."dayCount" IS '天数'; COMMENT ON COLUMN "calendarLife"."q" IS '定容容量(q)'; COMMENT ON COLUMN "calendarLife"."dq" IS '首次放电容量(dq)'; COMMENT ON COLUMN "calendarLife"."ddcr" IS '放电直流内阻(ddcr)'; COMMENT ON COLUMN "calendarLife"."cdcr" IS '充电直流内阻(cdcr)'; COMMENT ON COLUMN "calendarLife"."u" IS '电压(u)'; COMMENT ON COLUMN "calendarLife"."r" IS '交流内阻(r)'; COMMENT ON COLUMN "calendarLife"."qRetention" IS '容量保持率 qRetention=dq/q0d*100 (%)'; COMMENT ON COLUMN "calendarLife"."qRecovery" IS '容量恢复率 qRecovery=q/q0d*100 (%)'; COMMENT ON COLUMN "calendarLife"."ddcrGrowth" IS '放电DCR增长 ddcrGrowth=(ddcr/ddcr0d-1)*100 (%)'; COMMENT ON COLUMN "calendarLife"."cdcrGrowth" IS '充电DCR增长 cdcrGrowth=(cdcr/cdcr0d-1)*100 (%)'; COMMENT ON COLUMN "calendarLife"."uGrowth" IS '电压增长 uGrowth=(u/u0d-1)*100 (%)'; COMMENT ON COLUMN "calendarLife"."rGrowth" IS '内阻增长 rGrowth=(r/r0d-1)*100 (%)'; COMMENT ON COLUMN "calendarLife"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_6d952bed679566ee9fbf9705b6" ON "calendarLife" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c0a1720367278f3e08441fa20" ON "calendarLife" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82da85236b2c714da21e345649" ON "calendarLife" ("cellName") `);
        await queryRunner.query(`CREATE INDEX "IDX_30d3475a0fc66dd885eb27be68" ON "calendarLife" ("dayCount") `);
        await queryRunner.query(`COMMENT ON TABLE "calendarLife" IS '日历寿命数据表'`);
        await queryRunner.query(`CREATE TABLE "rawStepData" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "cycleNo" integer NOT NULL, "stepNo" integer NOT NULL, "stepSeqNo" integer NOT NULL, "stepType" character varying(32) NOT NULL, "stepTime" character varying(16), "capacity" numeric(18,6), "startVoltage" numeric(18,6), "endVoltage" numeric(18,6), "startCurrent" numeric(18,6), "endCurrent" numeric(18,6), "dataSource" character varying(16), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc062b38833a233a3cc9cc4e8f7" PRIMARY KEY ("id")); COMMENT ON COLUMN "rawStepData"."id" IS '主键ID'; COMMENT ON COLUMN "rawStepData"."experimentId" IS '实验ID'; COMMENT ON COLUMN "rawStepData"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "rawStepData"."cellName" IS '电芯名称'; COMMENT ON COLUMN "rawStepData"."cycleNo" IS '循环号'; COMMENT ON COLUMN "rawStepData"."stepNo" IS '工步号'; COMMENT ON COLUMN "rawStepData"."stepSeqNo" IS '工步序号'; COMMENT ON COLUMN "rawStepData"."stepType" IS '工步类型'; COMMENT ON COLUMN "rawStepData"."stepTime" IS '工步时间'; COMMENT ON COLUMN "rawStepData"."capacity" IS '容量/能量'; COMMENT ON COLUMN "rawStepData"."startVoltage" IS '起始电压(V)'; COMMENT ON COLUMN "rawStepData"."endVoltage" IS '结束电压(V)'; COMMENT ON COLUMN "rawStepData"."startCurrent" IS '起始电流(A)'; COMMENT ON COLUMN "rawStepData"."endCurrent" IS '结束电流(A)'; COMMENT ON COLUMN "rawStepData"."dataSource" IS '数据来源: formation(化成) / grading(定容)'; COMMENT ON COLUMN "rawStepData"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_786e9f48414b0f70f51368c3de" ON "rawStepData" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f9b4014565b62d8c3f20785e1" ON "rawStepData" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0fb78053c39b6e8dfe07da46d" ON "rawStepData" ("cellName") `);
        await queryRunner.query(`CREATE INDEX "IDX_30324211158baaabfe9d1ee99d" ON "rawStepData" ("dataSource") `);
        await queryRunner.query(`COMMENT ON TABLE "rawStepData" IS '原始工步数据表'`);
        await queryRunner.query(`CREATE TABLE "storageSwelling" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "qd1st" numeric(18,6), "dayCount" integer NOT NULL, "v" numeric(18,6), "vg" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_878eaff8931fc16879eaeb01f02" PRIMARY KEY ("id")); COMMENT ON COLUMN "storageSwelling"."id" IS '主键ID'; COMMENT ON COLUMN "storageSwelling"."experimentId" IS '实验ID'; COMMENT ON COLUMN "storageSwelling"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "storageSwelling"."cellName" IS '电芯名称'; COMMENT ON COLUMN "storageSwelling"."qd1st" IS '首圈放电容量(qd1st)'; COMMENT ON COLUMN "storageSwelling"."dayCount" IS '天数'; COMMENT ON COLUMN "storageSwelling"."v" IS '存储后电池体积(v)'; COMMENT ON COLUMN "storageSwelling"."vg" IS '产气量 vg=(v-v0d)/qd1st (mL/Ah)'; COMMENT ON COLUMN "storageSwelling"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_d2ef6164dc0f3784bccc42f050" ON "storageSwelling" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e667b5e0ae74b70574e06230d9" ON "storageSwelling" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3519a70e236c8bce0dd814d6ed" ON "storageSwelling" ("cellName") `);
        await queryRunner.query(`CREATE INDEX "IDX_38490d3b9b462636bd18c3c08d" ON "storageSwelling" ("dayCount") `);
        await queryRunner.query(`COMMENT ON TABLE "storageSwelling" IS '存储胀气数据表'`);
        await queryRunner.query(`CREATE TABLE "energyEfficiency" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "de" numeric(18,6), "ce" numeric(18,6), "ee" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c3994f423cb64f7d5d7cb1f743" PRIMARY KEY ("id")); COMMENT ON COLUMN "energyEfficiency"."id" IS '主键ID'; COMMENT ON COLUMN "energyEfficiency"."experimentId" IS '实验ID'; COMMENT ON COLUMN "energyEfficiency"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "energyEfficiency"."cellName" IS '电芯名称'; COMMENT ON COLUMN "energyEfficiency"."de" IS '放电能量(de)'; COMMENT ON COLUMN "energyEfficiency"."ce" IS '充电能量(ce)'; COMMENT ON COLUMN "energyEfficiency"."ee" IS '能量效率比 ee=de/ce'; COMMENT ON COLUMN "energyEfficiency"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_38e0360b7d29ea8e385e44f65c" ON "energyEfficiency" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e82fbf0ebe3fc55ce5b539b846" ON "energyEfficiency" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3ce55ad0080aa6314a21d8556" ON "energyEfficiency" ("cellName") `);
        await queryRunner.query(`COMMENT ON TABLE "energyEfficiency" IS '能效数据表'`);
        await queryRunner.query(`CREATE TABLE "dcrTest" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "q0" numeric(18,6), "du0" numeric(18,6), "du1" numeric(18,6), "di" numeric(18,6), "cu0" numeric(18,6), "cu1" numeric(18,6), "ci" numeric(18,6), "ddcr" numeric(18,6), "cdcr" numeric(18,6), "dRcProduct" numeric(18,6), "cRcProduct" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a92508c7dc4bbb1805016c48bdd" PRIMARY KEY ("id")); COMMENT ON COLUMN "dcrTest"."id" IS '主键ID'; COMMENT ON COLUMN "dcrTest"."experimentId" IS '实验ID'; COMMENT ON COLUMN "dcrTest"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "dcrTest"."cellName" IS '电芯名称'; COMMENT ON COLUMN "dcrTest"."q0" IS '测试前容量(q0)'; COMMENT ON COLUMN "dcrTest"."du0" IS '放电脉冲前电压(du0)'; COMMENT ON COLUMN "dcrTest"."du1" IS '放电脉冲后电压(du1)'; COMMENT ON COLUMN "dcrTest"."di" IS '放电脉冲电流(di)'; COMMENT ON COLUMN "dcrTest"."cu0" IS '充电脉冲前电压(cu0)'; COMMENT ON COLUMN "dcrTest"."cu1" IS '充电脉冲后电压(cu1)'; COMMENT ON COLUMN "dcrTest"."ci" IS '充电脉冲电流(ci)'; COMMENT ON COLUMN "dcrTest"."ddcr" IS '放电直流内阻 ddcr=|du1-du0|/di (Ω)'; COMMENT ON COLUMN "dcrTest"."cdcr" IS '充电直流内阻 cdcr=|cu1-cu0|/ci (Ω)'; COMMENT ON COLUMN "dcrTest"."dRcProduct" IS '放电R-C乘积 dRcProduct=q0*ddcr (Ah·Ω)'; COMMENT ON COLUMN "dcrTest"."cRcProduct" IS '充电R-C乘积 cRcProduct=q0*cdcr (Ah·Ω)'; COMMENT ON COLUMN "dcrTest"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_0506c37b88447691102a295d2d" ON "dcrTest" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c649caf7b0622251228dfa284f" ON "dcrTest" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_20ee83c2eb43aa42ef637fe670" ON "dcrTest" ("cellName") `);
        await queryRunner.query(`COMMENT ON TABLE "dcrTest" IS '直流内阻测试数据表'`);
        await queryRunner.query(`CREATE TABLE "fastCharge" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cellName" character varying(64) NOT NULL, "c0" numeric(18,6), "providedFastChargeTime" numeric(18,6), "computedFastChargeTime" numeric(18,6), "steps" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5566b4ad0635d67090f8d0423de" PRIMARY KEY ("id")); COMMENT ON COLUMN "fastCharge"."id" IS '主键ID'; COMMENT ON COLUMN "fastCharge"."experimentId" IS '实验ID'; COMMENT ON COLUMN "fastCharge"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "fastCharge"."cellName" IS '电芯名称'; COMMENT ON COLUMN "fastCharge"."c0" IS '标称容量(c0)'; COMMENT ON COLUMN "fastCharge"."providedFastChargeTime" IS '提供的快充时间'; COMMENT ON COLUMN "fastCharge"."computedFastChargeTime" IS '计算10%-80%SOC快充时间 computedFastChargeTime (min)'; COMMENT ON COLUMN "fastCharge"."steps" IS '快充工步数据'; COMMENT ON COLUMN "fastCharge"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_a718c38548eab49b2fd07ace3e" ON "fastCharge" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90b6f7848a339af2c596a99879" ON "fastCharge" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fad8c45fec0a5a952e4a8dbe75" ON "fastCharge" ("cellName") `);
        await queryRunner.query(`COMMENT ON TABLE "fastCharge" IS '快充时间工步表'`);
        await queryRunner.query(`CREATE TABLE "htCycle" ("id" uuid NOT NULL, "experimentId" uuid NOT NULL, "attachmentId" uuid, "cycle" integer NOT NULL, "cellName" character varying(64) NOT NULL, "ironDissolution" numeric(18,6), "dischargeCapacity" numeric(18,6), "capacityRetention" numeric(18,6), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aaae4dc9f454267bebc28013097" PRIMARY KEY ("id")); COMMENT ON COLUMN "htCycle"."id" IS '主键ID'; COMMENT ON COLUMN "htCycle"."experimentId" IS '实验ID'; COMMENT ON COLUMN "htCycle"."attachmentId" IS '关联附件ID'; COMMENT ON COLUMN "htCycle"."cycle" IS '循环次数'; COMMENT ON COLUMN "htCycle"."cellName" IS '电芯名称'; COMMENT ON COLUMN "htCycle"."ironDissolution" IS '铁溶出量'; COMMENT ON COLUMN "htCycle"."dischargeCapacity" IS '放电容量'; COMMENT ON COLUMN "htCycle"."capacityRetention" IS '容量保持率'; COMMENT ON COLUMN "htCycle"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_96a8d5541d8d96454458354182" ON "htCycle" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_05af187b160d28e4914107888d" ON "htCycle" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ce363c5675f2544482b934c00" ON "htCycle" ("cycle") `);
        await queryRunner.query(`CREATE INDEX "IDX_45fc54a02e2cceff85b91dcb23" ON "htCycle" ("cellName") `);
        await queryRunner.query(`COMMENT ON TABLE "htCycle" IS '高温循环数据表'`);
        await queryRunner.query(`CREATE TABLE "cellGroup" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "name" character varying(64) NOT NULL, "color" character varying(9) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "matchMode" character varying(16) NOT NULL, "matchValue" character varying(128), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ec4e9aaa437475cd54730c9ff26" PRIMARY KEY ("id")); COMMENT ON COLUMN "cellGroup"."id" IS '主键ID'; COMMENT ON COLUMN "cellGroup"."projectId" IS '项目ID'; COMMENT ON COLUMN "cellGroup"."name" IS '分组名称（如 "方案A", "对照组"）'; COMMENT ON COLUMN "cellGroup"."color" IS '十六进制色值（如 "#1d74f5"）'; COMMENT ON COLUMN "cellGroup"."sortOrder" IS '排序权重'; COMMENT ON COLUMN "cellGroup"."matchMode" IS '匹配模式: prefix | manual'; COMMENT ON COLUMN "cellGroup"."matchValue" IS '前缀模式下存前缀值; manual 模式下为空'; COMMENT ON COLUMN "cellGroup"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_6d629a63241556d5bb727fd624" ON "cellGroup" ("projectId") `);
        await queryRunner.query(`COMMENT ON TABLE "cellGroup" IS '电池分组定义表'`);
        await queryRunner.query(`CREATE TABLE "cellGroupMember" ("id" uuid NOT NULL, "groupId" uuid NOT NULL, "cellIdentifier" character varying(128) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ccee40464c2698ae92e5347f0a8" PRIMARY KEY ("id")); COMMENT ON COLUMN "cellGroupMember"."id" IS '主键ID'; COMMENT ON COLUMN "cellGroupMember"."groupId" IS '分组ID'; COMMENT ON COLUMN "cellGroupMember"."cellIdentifier" IS '电芯标识符（cellName 或 cellId）'; COMMENT ON COLUMN "cellGroupMember"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_54c9767f16a334c9f7fcab0529" ON "cellGroupMember" ("groupId") `);
        await queryRunner.query(`COMMENT ON TABLE "cellGroupMember" IS '手动分组电芯表'`);
        await queryRunner.query(`CREATE TABLE "pickedCell" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "cellId" character varying(64) NOT NULL, "pickedBy" character varying(16) NOT NULL DEFAULT 'auto', "testType" character varying(64), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf6b7b9b12448fd5740a21b581d" PRIMARY KEY ("id")); COMMENT ON COLUMN "pickedCell"."id" IS '主键ID'; COMMENT ON COLUMN "pickedCell"."projectId" IS '项目ID'; COMMENT ON COLUMN "pickedCell"."cellId" IS '电芯编号'; COMMENT ON COLUMN "pickedCell"."pickedBy" IS '挑选方式(auto/manual)'; COMMENT ON COLUMN "pickedCell"."testType" IS '分配的测试类型'; COMMENT ON COLUMN "pickedCell"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_773a1cd1d1b95667c2adb14306" ON "pickedCell" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b84118947015ad7fa6e55f29b" ON "pickedCell" ("cellId") `);
        await queryRunner.query(`COMMENT ON TABLE "pickedCell" IS '电池挑选记录表'`);
        await queryRunner.query(`CREATE TABLE "workflowTemplate" ("id" uuid NOT NULL, "name" character varying(128) NOT NULL, "description" text, "isDefault" boolean NOT NULL DEFAULT false, "steps" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d76d84196c57d61a68bee05476" PRIMARY KEY ("id")); COMMENT ON COLUMN "workflowTemplate"."id" IS '主键ID'; COMMENT ON COLUMN "workflowTemplate"."name" IS '模板名称'; COMMENT ON COLUMN "workflowTemplate"."description" IS '模板描述'; COMMENT ON COLUMN "workflowTemplate"."isDefault" IS '是否系统内置默认模板'; COMMENT ON COLUMN "workflowTemplate"."steps" IS '步骤定义数组'; COMMENT ON COLUMN "workflowTemplate"."createdAt" IS '创建时间'`);
        await queryRunner.query(`COMMENT ON TABLE "workflowTemplate" IS '流程模板表'`);
        await queryRunner.query(`CREATE TABLE "workflowInstance" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "templateId" uuid NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'Active', "currentStepIndex" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fad03237c3870d17c0cc5807dd0" PRIMARY KEY ("id")); COMMENT ON COLUMN "workflowInstance"."id" IS '主键ID'; COMMENT ON COLUMN "workflowInstance"."projectId" IS '项目ID'; COMMENT ON COLUMN "workflowInstance"."templateId" IS '模板ID'; COMMENT ON COLUMN "workflowInstance"."status" IS '状态(Active/Completed/Paused)'; COMMENT ON COLUMN "workflowInstance"."currentStepIndex" IS '当前步骤索引'; COMMENT ON COLUMN "workflowInstance"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_b98a830d9738b7375f031d94c1" ON "workflowInstance" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_18fd73aa1edb4f98cf218e850a" ON "workflowInstance" ("templateId") `);
        await queryRunner.query(`COMMENT ON TABLE "workflowInstance" IS '流程实例表'`);
        await queryRunner.query(`CREATE TABLE "workflowStepAssignment" ("id" uuid NOT NULL, "workflowInstanceId" uuid NOT NULL, "stepName" character varying(64) NOT NULL, "stepIndex" integer NOT NULL, "assignedUserId" uuid, "status" character varying(32) NOT NULL DEFAULT 'pending', "canViewOtherSteps" boolean NOT NULL DEFAULT false, "canViewInternalCode" boolean NOT NULL DEFAULT false, "visibleToUserIds" jsonb, "isParallelGroup" boolean NOT NULL DEFAULT false, "parentStepName" character varying(64), "completedAt" TIMESTAMP, "completedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_87dba81143a1752964005283f99" PRIMARY KEY ("id")); COMMENT ON COLUMN "workflowStepAssignment"."id" IS '主键ID'; COMMENT ON COLUMN "workflowStepAssignment"."workflowInstanceId" IS '流程实例ID'; COMMENT ON COLUMN "workflowStepAssignment"."stepName" IS '步骤名称(key)'; COMMENT ON COLUMN "workflowStepAssignment"."stepIndex" IS '步骤序号'; COMMENT ON COLUMN "workflowStepAssignment"."assignedUserId" IS '分配执行人ID'; COMMENT ON COLUMN "workflowStepAssignment"."status" IS '步骤状态(pending/in_progress/completed/skipped)'; COMMENT ON COLUMN "workflowStepAssignment"."canViewOtherSteps" IS '能否查看其他步骤'; COMMENT ON COLUMN "workflowStepAssignment"."canViewInternalCode" IS '能否查看内部代码'; COMMENT ON COLUMN "workflowStepAssignment"."visibleToUserIds" IS '允许查看该步骤的其他人员ID列表'; COMMENT ON COLUMN "workflowStepAssignment"."isParallelGroup" IS '是否为并行组节点(如testing)'; COMMENT ON COLUMN "workflowStepAssignment"."parentStepName" IS '父级并行组步骤名称'; COMMENT ON COLUMN "workflowStepAssignment"."completedAt" IS '完成时间'; COMMENT ON COLUMN "workflowStepAssignment"."completedBy" IS '完成人ID'; COMMENT ON COLUMN "workflowStepAssignment"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_a95f7b90333f01089f76330136" ON "workflowStepAssignment" ("workflowInstanceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_56ba349d31e3c36e7a4ce88c68" ON "workflowStepAssignment" ("stepIndex") `);
        await queryRunner.query(`CREATE INDEX "IDX_5809f5bb4cd206f29f3e88efea" ON "workflowStepAssignment" ("assignedUserId") `);
        await queryRunner.query(`COMMENT ON TABLE "workflowStepAssignment" IS '流程步骤分配表'`);
        await queryRunner.query(`CREATE TABLE "experimentDesign" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "rowIndex" integer NOT NULL, "group" character varying(128) NOT NULL, "moleculeName" character varying(255) NOT NULL, "chineseName" character varying(128), "molecularStructure" text, "cas" character varying(64) NOT NULL, "designPrinciple" text, "internalCode" character varying(128) NOT NULL, "isRedundancy" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_361b0e62539a89932a54403f187" PRIMARY KEY ("id")); COMMENT ON COLUMN "experimentDesign"."id" IS '主键ID'; COMMENT ON COLUMN "experimentDesign"."projectId" IS '项目ID'; COMMENT ON COLUMN "experimentDesign"."rowIndex" IS '行序号'; COMMENT ON COLUMN "experimentDesign"."group" IS '分组'; COMMENT ON COLUMN "experimentDesign"."moleculeName" IS '分子名称'; COMMENT ON COLUMN "experimentDesign"."chineseName" IS '中文简称'; COMMENT ON COLUMN "experimentDesign"."molecularStructure" IS '分子结构图URL'; COMMENT ON COLUMN "experimentDesign"."cas" IS 'CAS号'; COMMENT ON COLUMN "experimentDesign"."designPrinciple" IS '设计原理'; COMMENT ON COLUMN "experimentDesign"."internalCode" IS '内部代码(自动生成)'; COMMENT ON COLUMN "experimentDesign"."isRedundancy" IS '是否为冗余行'; COMMENT ON COLUMN "experimentDesign"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_ef0d2789fd7256c332b4d2bdc0" ON "experimentDesign" ("projectId") `);
        await queryRunner.query(`COMMENT ON TABLE "experimentDesign" IS '实验设计表'`);
        await queryRunner.query(`CREATE TABLE "reagentProcurement" ("id" uuid NOT NULL, "projectId" uuid NOT NULL, "experimentDesignId" uuid, "moleculeName" character varying(255) NOT NULL, "supplier" character varying(255), "batchNo" character varying(128), "purity" character varying(64), "quantity" character varying(64), "isValid" boolean NOT NULL DEFAULT true, "remark" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd3b9f8a8125a662f0087cde720" PRIMARY KEY ("id")); COMMENT ON COLUMN "reagentProcurement"."id" IS '主键ID'; COMMENT ON COLUMN "reagentProcurement"."projectId" IS '项目ID'; COMMENT ON COLUMN "reagentProcurement"."experimentDesignId" IS '关联实验设计ID'; COMMENT ON COLUMN "reagentProcurement"."moleculeName" IS '分子名称'; COMMENT ON COLUMN "reagentProcurement"."supplier" IS '供应商'; COMMENT ON COLUMN "reagentProcurement"."batchNo" IS '批号'; COMMENT ON COLUMN "reagentProcurement"."purity" IS '纯度'; COMMENT ON COLUMN "reagentProcurement"."quantity" IS '数量'; COMMENT ON COLUMN "reagentProcurement"."isValid" IS '是否有效(采购到)'; COMMENT ON COLUMN "reagentProcurement"."remark" IS '备注'; COMMENT ON COLUMN "reagentProcurement"."createdAt" IS '创建时间'`);
        await queryRunner.query(`CREATE INDEX "IDX_893d1e08ac57393bc553797745" ON "reagentProcurement" ("projectId") `);
        await queryRunner.query(`COMMENT ON TABLE "reagentProcurement" IS '试剂采购表'`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_c714b0a5eaf71cc3a36c242d2e9" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_c714b0a5eaf71cc3a36c242d2e9"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`COMMENT ON TABLE "reagentProcurement" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_893d1e08ac57393bc553797745"`);
        await queryRunner.query(`DROP TABLE "reagentProcurement"`);
        await queryRunner.query(`COMMENT ON TABLE "experimentDesign" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef0d2789fd7256c332b4d2bdc0"`);
        await queryRunner.query(`DROP TABLE "experimentDesign"`);
        await queryRunner.query(`COMMENT ON TABLE "workflowStepAssignment" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5809f5bb4cd206f29f3e88efea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56ba349d31e3c36e7a4ce88c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a95f7b90333f01089f76330136"`);
        await queryRunner.query(`DROP TABLE "workflowStepAssignment"`);
        await queryRunner.query(`COMMENT ON TABLE "workflowInstance" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18fd73aa1edb4f98cf218e850a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b98a830d9738b7375f031d94c1"`);
        await queryRunner.query(`DROP TABLE "workflowInstance"`);
        await queryRunner.query(`COMMENT ON TABLE "workflowTemplate" IS NULL`);
        await queryRunner.query(`DROP TABLE "workflowTemplate"`);
        await queryRunner.query(`COMMENT ON TABLE "pickedCell" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b84118947015ad7fa6e55f29b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_773a1cd1d1b95667c2adb14306"`);
        await queryRunner.query(`DROP TABLE "pickedCell"`);
        await queryRunner.query(`COMMENT ON TABLE "cellGroupMember" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54c9767f16a334c9f7fcab0529"`);
        await queryRunner.query(`DROP TABLE "cellGroupMember"`);
        await queryRunner.query(`COMMENT ON TABLE "cellGroup" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d629a63241556d5bb727fd624"`);
        await queryRunner.query(`DROP TABLE "cellGroup"`);
        await queryRunner.query(`COMMENT ON TABLE "htCycle" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45fc54a02e2cceff85b91dcb23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce363c5675f2544482b934c00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05af187b160d28e4914107888d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96a8d5541d8d96454458354182"`);
        await queryRunner.query(`DROP TABLE "htCycle"`);
        await queryRunner.query(`COMMENT ON TABLE "fastCharge" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fad8c45fec0a5a952e4a8dbe75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90b6f7848a339af2c596a99879"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a718c38548eab49b2fd07ace3e"`);
        await queryRunner.query(`DROP TABLE "fastCharge"`);
        await queryRunner.query(`COMMENT ON TABLE "dcrTest" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20ee83c2eb43aa42ef637fe670"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c649caf7b0622251228dfa284f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0506c37b88447691102a295d2d"`);
        await queryRunner.query(`DROP TABLE "dcrTest"`);
        await queryRunner.query(`COMMENT ON TABLE "energyEfficiency" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3ce55ad0080aa6314a21d8556"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e82fbf0ebe3fc55ce5b539b846"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38e0360b7d29ea8e385e44f65c"`);
        await queryRunner.query(`DROP TABLE "energyEfficiency"`);
        await queryRunner.query(`COMMENT ON TABLE "storageSwelling" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38490d3b9b462636bd18c3c08d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3519a70e236c8bce0dd814d6ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e667b5e0ae74b70574e06230d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2ef6164dc0f3784bccc42f050"`);
        await queryRunner.query(`DROP TABLE "storageSwelling"`);
        await queryRunner.query(`COMMENT ON TABLE "rawStepData" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30324211158baaabfe9d1ee99d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0fb78053c39b6e8dfe07da46d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f9b4014565b62d8c3f20785e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_786e9f48414b0f70f51368c3de"`);
        await queryRunner.query(`DROP TABLE "rawStepData"`);
        await queryRunner.query(`COMMENT ON TABLE "calendarLife" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30d3475a0fc66dd885eb27be68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82da85236b2c714da21e345649"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c0a1720367278f3e08441fa20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d952bed679566ee9fbf9705b6"`);
        await queryRunner.query(`DROP TABLE "calendarLife"`);
        await queryRunner.query(`COMMENT ON TABLE "processData" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3f758e69283ec92a398ee6585"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b024f6e1e27264bcb8109d6d44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0504697d5e858d8ee01aa0cbe8"`);
        await queryRunner.query(`DROP TABLE "processData"`);
        await queryRunner.query(`COMMENT ON TABLE "notification" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_080ab397c379af09b9d2169e5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ced25315eb974b73391fb1c81"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`COMMENT ON TABLE "experiment_comment" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd6bb290d536ed57958a54bd84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f4c51881e0109ea728240a4ef"`);
        await queryRunner.query(`DROP TABLE "experiment_comment"`);
        await queryRunner.query(`COMMENT ON TABLE "versionHistory" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a48644f8cf5c8a91b72017b4e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c549e9092793b630f713f52240"`);
        await queryRunner.query(`DROP TABLE "versionHistory"`);
        await queryRunner.query(`COMMENT ON TABLE "attachment" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce931a70e87bef5768e1ee3b10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_879e0f0818cc2e9294aa9fdcd9"`);
        await queryRunner.query(`DROP TABLE "attachment"`);
        await queryRunner.query(`COMMENT ON TABLE "inventory" IS NULL`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`COMMENT ON TABLE "experiment" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64493affb7ed37cb8c0b58ac0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f55aeb096e324c495f65d0884d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_515a4754daa77993362776c559"`);
        await queryRunner.query(`DROP TABLE "experiment"`);
        await queryRunner.query(`COMMENT ON TABLE "experimentCollaborator" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b59fc13761df821a62b4f42d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb2aacc1444724703a3c1407fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05ba4be00496a7f7b50c8cffae"`);
        await queryRunner.query(`DROP TABLE "experimentCollaborator"`);
        await queryRunner.query(`COMMENT ON TABLE "project" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c714b0a5eaf71cc3a36c242d2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc881566db51356dbba057458"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`COMMENT ON TABLE "user" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c28e52f758e7bbc53828db9219"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`COMMENT ON TABLE "role" IS NULL`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
